name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up UnrealPak
      run: |
        # 如果需要，你可以下载并解压UnrealPakSwitchv10工具包
        # 假设工具已经放在仓库中，跳过下载步骤

    - name: Run CMD script
      run: |
        # 执行所有CMD命令
        cmd /c "
        UnrealPakSwitchv10\UnrealLocres.exe import UnrealPakSwitchv10\Game.locres Game.csv
        move \"UnrealPakSwitchv10\Game.locres.new\" \"UnrealPakSwitchv10\ch4_pro\Content\Localization\Game\en\"
        del \"UnrealPakSwitchv10\ch4_pro\Content\Localization\Game\en\Game.locres\"
        rename \"UnrealPakSwitchv10\ch4_pro\Content\Localization\Game\en\Game.locres.new\" \"Game.locres\"
        UnrealPakSwitchv10\v5.3\2\3\UnrealPak.exe ..\..\..\..\ch4_pro-Windows_p.pak -Create=..\..\..\ch4_pro.txt -compress
        "

    - name: Zip the output file
      run: |
        # 使用powershell打包生成的ch4_pro-Windows_p.pak文件为zip
        powershell Compress-Archive -Path "ch4_pro-Windows_p.pak" -DestinationPath "ch4_pro-Windows_p.zip"

    - name: Get current date for release title
      id: date
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d_%H-%M-%S')"

    - name: Upload zip to GitHub Releases
      uses: ncipollo/release-action@v1
      with:
        tag: 'v1.0.0'  # 你可以根据需要调整版本号
        files: 'ch4_pro-Windows_p.zip'
        name: 'PoppyPlaytime-Chapter4中文补丁-${{ steps.date.outputs.date }}'
